[Application Options]
datadir=~/.lnd
rpclisten=127.0.0.1:10010
restlisten=127.0.0.1:8081

[Bitcoin]
bitcoin.node=electrum
bitcoin.testnet=true

[electrum]
server=testnet.aranguren.org:51002
tls=true
validateservercert=true
